### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by yashiki2049** [yashiki2049/furima-32048#9]
フリマアプリを作成し、デプロイ致しました。
ご確認よろしくお願い致します。

# URL
https://furima-32048.herokuapp.com/
# Basic認証
 - ID [admin]
 - パスワード [2222]
# 出品者用ユーザー情報
**ユーザー名：マイ**
 - メールアドレス [pop@mail]
 - パスワード [mmm111]
# 購入者用ユーザー情報
**ユーザー名：タロウ**
 - メールアドレス [pop-2@mail]
 - パスワード [mmm222]
# 購入用カード情報
 - カード番号 [4242424242424242]
 - 期限 [10 / 25] (登録日より未来)
 - セキュリティコード [123]

**Comment by snkw-works** [comment]
ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像](https://user-images.githubusercontent.com/54050089/101301888-7b8f7a00-387d-11eb-9085-1380b0513878.png)

**Comment by yashiki2049** [comment]
ご確認頂きありがとうございました！
学習したこと、教えて頂いたことを生かしてこの先も頑張ってまいります😆✨
